name: Waka Time Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 24hrs at 6am IST
    - cron: "0 */12 * * *"

jobs:
  update-readme:
    name: Update Profile README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: Waka Time Update
          SHOW_TITLE: true