name: Update Image Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 24hrs at 6am IST
    - cron: "0 */12 * * *"

jobs:
  update-readme:
    name: Update Image README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/update-readme-image@main
