name: Waka Time Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12 UTC everyday
    - cron: "0 15 * * *"

jobs:
  update-readme:
    name: Update Profile README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: Waka Time Update
          SHOW_TITLE: true
